#!/bin/bash
#
# Generate the displaylink sleep hook script.
#
# We completely replace the upstream suspend/resume functions rather than
# trying to patch around the upstream IPC mechanism (PmMessagesPort_in/out).
# The upstream approach writes to named pipes that may not exist yet, may be
# regular files instead of FIFOs, or may block indefinitely. Instead we:
#
#   Pre-suspend:  set a guard file and stop the service immediately.
#   Post-resume:  wait for USB re-enumeration, start the service, re-trigger
#                 udev so DisplayLinkManager discovers the dock, then remove
#                 the guard file.
#
# The guard file /run/displaylink-suspending prevents udev's stop_service()
# from racing with us during the xHCI reinit window on wake.

cat << 'SLEEP_HOOK'
#!/usr/bin/bash
# DisplayLink sleep hook — generated by displaylink-sleep-extractor.sh

suspend_displaylink-driver()
{
  # Mark that we are entering the suspend/resume window so that udev's
  # stop_service() ignores transient USB disconnect events (e.g. from
  # xHCI reinit on Apple Silicon).
  touch /run/displaylink-suspending

  # Stop the service now. DisplayLinkManager ignores SIGTERM so the unit
  # is configured with KillSignal=SIGKILL; this returns quickly.
  systemctl stop displaylink-driver.service 2>/dev/null
}

resume_displaylink-driver()
{
  # Give the xHCI controller time to finish re-enumerating USB devices
  # after wake. On Apple Silicon the dock momentarily disconnects during
  # the reinit window; waiting avoids starting before it reappears.
  sleep 3

  # Start a fresh instance of the service.
  systemctl start displaylink-driver.service

  # Re-trigger udev add events for any connected DisplayLink devices so
  # that DisplayLinkManager discovers the dock and reconnects to evdi.
  grep -lw 17e9 /sys/bus/usb/devices/*/idVendor 2>/dev/null | while IFS= read -r f; do
    udevadm trigger --action=add "$(dirname "$f")"
  done

  # Clean up the guard file now that the service is back.
  rm -f /run/displaylink-suspending
}

main_systemd()
{
  case "$1/$2" in
  pre/*)
    suspend_displaylink-driver
    ;;
  post/*)
    resume_displaylink-driver
    ;;
  esac
}

main_pm()
{
  case "$1" in
    suspend|hibernate)
      suspend_displaylink-driver
      ;;
    resume|thaw)
      resume_displaylink-driver
      ;;
  esac
  true
}

DIR=$(cd "$(dirname "$0")" && pwd)

if [[ $DIR == *systemd* ]]; then
  main_systemd "$@"
elif [[ $DIR == *pm* ]]; then
  main_pm "$@"
fi
SLEEP_HOOK
